apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "test"
spec:
  stages:
  - name: dev
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: functional
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
      - name: release
    - name: delivery-direct
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: functional
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
      - name: release
  - name: staging
    sequences:
    - name: delivery
      triggeredOn:
      - event: dev.delivery.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: blue_green_service
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
      - name: release
    - name: rollback
      triggeredOn:
      - event: staging.delivery.finished
        selector:
          match:
            result: fail
      tasks:
      - name: rollback
    - name: delivery-direct
      triggeredOn:
      - event: dev.delivery-direct.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
      - name: release
  - name: production
    sequences:
    - name: delivery
      triggeredOn:
      - event: staging.delivery.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: blue_green_service
      - name: approval
        properties:
          pass: manual
          warning: manual
      - name: release
    - name: rollback
      triggeredOn:
      - event: production.delivery.finished
        selector:
          match:
            result: fail
      tasks:
      - name: rollback
    - name: delivery-direct
      triggeredOn:
      - event: staging.delivery-direct.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: approval
        properties:
          pass: manual
          warning: manual
      - name: release
